# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8a52d31851d3c415fd86a044d5bb62c396e3d62c62c34bad9d8b0ea0536dbd12f72072cf2da4719874f99f47862c57fa98edb60d86cdcd880c005a252cc900c

test:
  secret_key_base: 357922f9b2f9ea3af825878d68bc4a1709ed7ae5406e56f0e98bb1d3742e9a368b430a27930e28b3c20429cb5cdba4f59c4d247e872a2a6d7d7bf9a87090313b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
